### ISSUE TITLE
Основное подключение сделать в настройках

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#10]
Переключение из панели нужно убрать. Наш основной кейс - 1 человек - 1 инстанс, ему не нужен переключатель инстансов так сильно на виду.

**Comment by yellow-sky** [comment]
Не очень согласен. У меня 5ть инстансов и я их постоянно юзаю. Это очень
удобно. А так придется по 10 кликов делать.
11.05.2016 23:06 пользователь "Maxim Dubinin" <notifications@github.com>
написал:

**Comment by simgislab** [comment]
переключение инстансов/НГВ оставить в настройках
