### ISSUE TITLE
'long division or modulo by zero' error trying to upload KML layer

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#108]
1. Added a KML (points)
2. Trying to send it to nextgis.com

error on Win 7 (16.2.150):

>[Import 'Built sites Point'] Received unknown error. See logs.
>long division or modulo by zero

The same works fine on Ubuntu.

data: https://www.dropbox.com/s/dx5tpt8mfwkoqs5/Built-sites.kml?dl=0

**Comment by MikhanGusev** [comment]
Cannot reproduce on Win 10 x64 both in QGIS 2/3 and Connect 0.12.4
