### ISSUE TITLE
Explanation for username and password as a label with link

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#111]
User should have a clear answer to a question:

Where do I get these?
Где взять имя пользователя и пароль?

To solve it, add a label on a GUI with a link to a specific section of the manual.

**Comment by alisovenko** [comment]
Done in 0.9.3

**Comment by alisovenko** [comment]
What link url should be used?

**Comment by simgislab** [comment]
http://docs.nextgis.com/docs_ngcom/source/ngqgis_connect.html#ngcom-ngqgis-connect-connection
and
http://docs.nextgis.ru/docs_ngcom/source/ngqgis_connect.html#ngcom-ngqgis-connect-connection

**Comment by simgislab** [comment]
link should always be clickable, even for gues
![connect](https://cloud.githubusercontent.com/assets/172806/21931258/f25954a8-d9b3-11e6-9ad4-909cd38dce8b.png)
