### ISSUE TITLE
Wrong web map extent is set

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#117]
When uploading this layer as a project
[Maumbai_Buildings_Top_Elevation_21032017.zip](https://github.com/nextgis/nextgis_connect/files/865118/Maumbai_Buildings_Top_Elevation_21032017.zip)

top and bottom are zeroes

**Comment by alisovenko** [comment]
Can not reproduce with version 0.10.6
Probably already fixed.
