### ISSUE TITLE
При загрузке слоя в ngw, в названии стиля не нужно добавлять -style 

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#118]
Сейчас когда создаёшь слой, то потом когда создаёшь веб-карту, в списке слоёв везде пишется -style. Его всегда приходится стирать вручную.
![Снимок экрана от 2019-12-04 19-06-01](https://user-images.githubusercontent.com/4630662/70160459-95770980-16cb-11ea-8cbb-b2235ce4a92e.png)

**Comment by trolleway** [comment]
Я сделал pull-request в зависимую библиотеку, в этом репозитории нужно будет обновить ссылку на git submodule

**Comment by simgislab** [comment]
implemented
