### ISSUE TITLE
Set raster transparency at the webmap on project import

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#120]
Upload a raster with transparency set as a project. The transparency will be ignored. Thats because raster style is a dummy.

While we're working on that, as a temporary workaround we can move transparency setting from raster (if it is set) to a layer's transparency at the Web map level.

It is different from how we do with vector, but we have a full style in vector case, not a dummy.

Obviously this will only work if the project is imported, not a layer.

**Comment by MikhanGusev** [comment]
The transparency is now set in 0.12.5 as a part of QGIS style which is uploaded for any raster layer by default
