### ISSUE TITLE
Downloading a vector layer from Web GIS fails if it's under HTTPS

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#126]
tried on http://maxim.nextgis.com

**Comment by alisovenko** [comment]
I suppose this is not connect error.
Such geojson url cannot be added to NextGIS QGIS directly (QGIS 2.14).
But you can do it in QGIS 2.18

I suppose this is NextGIS QGIS task.

**Comment by MikhanGusev** [comment]
Fixed in 0.12.2
