### ISSUE TITLE
While uploading raster,  nodata value should be used

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#129]
Шаги для воспроизведения:
* Скачать растр с openaerialmap: https://map.openaerialmap.org/#/37.670027017593384,55.61763692376961,16/12031010112210231/599bd8f746e19904aab0a947?resolution=high&_k=cb5zhk
* Открыть его в qgis, настроить nodata 0. Края будут прозрачными.
* Загрузить его в ngw, положить на веб-карту. Края будут чёрными.

![2017-08-25 12-47-22](https://user-images.githubusercontent.com/4630662/29709046-91d5d5bc-8993-11e7-9d1c-2e98cf9925fa.png)
![2017-08-25 12-49-14](https://user-images.githubusercontent.com/4630662/29709097-d07228ca-8993-11e7-94b0-3f15b921e043.png)

**Comment by simgislab** [comment]
работает с новыми стилями
