### ISSUE TITLE
Layer upload should not fail if NGW server not have QGIS rendering

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#132]
NGW можно поставить без рендера QGIS. 
При загрузке слоя туда, плагин nextgis connect выдаёт панель с ошибкой "Неизвестный класс ресурса 'qgis_vector_style'."
Слой в вебе появляется, но список слоёв в модуле не обновляется.

Желаемое поведение:
Ответ сервера "Неизвестный класс ресурса 'qgis_vector_style'." не должен считаться такой серьёзной ошибкой, пользователю должно где-то писаться сообщение: "Слой загружен, стили qgis этот сервер не поддерживает"

**Comment by ivanbarsukov** [comment]
A rare problem. We're closing it for now, feel free to reopen it if still relevant.
