### ISSUE TITLE
DataError, can't upload a layer in unicode in field names

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#141]
Attached are two layers. Both have unicode field names. But this probably is not the problem.

load - loads fine
noload - fails to load producing an error

```
Unknown exception 'DataError'..
URL: https://maxim.nextgis.com/api/resource/
```

[test.zip](https://github.com/nextgis/nextgis_connect/files/1844109/test.zip)

**Comment by simgislab** [comment]
see https://github.com/nextgis/nextgis_connect/issues/124

**Comment by edpop** [comment]
Проверил. Баг в NGW (по крайней мере для load, noload - сам QGIS не понимает).

**Comment by edpop** [comment]
Со стороны NGW баг поправили, оба слоя грузятся через GUI. На стороне плагина продолжаются ошибки.

**Comment by ivanbarsukov** [comment]
Fixed
