### ISSUE TITLE
Сообщение об ошибке отличается от веб интерфейса

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_connect#146]
При загрузке из QGIS пишет:

```
2018-06-08T12:19:14	0	 msgstr "Неизвестная ошибка 'InternalError'..
			URL: http://bishop.nextgis.com/api/resource/
```

В веб интерфейсе:

![2018-06-08 12 30 09](https://user-images.githubusercontent.com/1708122/41150988-10c32cba-6b18-11e8-98b4-669f4966ea24.png)

**Comment by ivanbarsukov** [comment]
Released in 2.0
