### ISSUE TITLE
Обрезаются поля на кириллице при загрузке в Веб ГИС

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#149]
1. Загружаем в NGQ
2. Отправляем в Веб ГИС

Результат: половина полей - теряют половину названия.

[Здания_Ак_ПРОЕКТ-centroids-_26.zip](https://github.com/nextgis/nextgis_connect/files/2367272/_._.-centroids-_26.zip)

**Comment by BishopGIS** [comment]
Только сегодня проверили, что имена полей на русском невалидные. 
Предлагаю следующий подход:
1 Имена полей транслитерировать
2 Если в проекте нет псевдонимов, то исходные имена переносить в псевдонимы в веб ГИС

**Comment by edpop** [comment]
В данном примере данные уже покалечены шейпом. Про загрузку полей с кириллицей работает тикет [тут](https://github.com/nextgis/nextgis_connect/issues/149)
