### ISSUE TITLE
Bad connection through Connect crashes QGIS

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#150]
1. Sucessfully connect to your Web GIS
2. Close QGIS
3. Go to service settings and mess up the settings, for example change http to https (where https is not available).
4. Try starting QGIS again

QGIS will start, Connect will try to connect, can't, crashes all. Result - QGIS can't be started.

Situation is typical when connection settings change or Web GIS is unavailable (downtime or something like this)

**Comment by alisovenko** [comment]
Fixed in 0.11.3
