### ISSUE TITLE
Create WMS failed

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_connect#153]
Error from user QGIS log:

```
2019-04-17T16:15:41	1	Traceback (most recent call last):
			  File "C:/NextGIS/share/ngqgis/python/plugins\nextgis_connect\tree_panel.py", line 933, in create_wms_service
			    if not dlg.needCreateNewStyle() and dlg.selectedStyle():
			AttributeError: 'NGWLayerStyleChooserDialog' object has no attribute 'needCreateNewStyle'
```

If user try to create WMS from layer or layer style error occurred.

**Comment by npkfrolov** [comment]
"Overwrite selected layer" дает ошибку MSG: Bad http comunication.Response status code is 502
Тот же слой (postgis) заново отлично создается.

**Comment by simgislab** [comment]
need vector layer data sample or link to this layer

problem with its fields most probably

**Comment by simgislab** [comment]
no feedback
