### ISSUE TITLE
Apply WFS layer(s) style(s) when adding WFS service

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#155]
1. User creates a WFS service for a vector layer
2. It gets added to QGIS, but the default legend.

It would be nice to add with the QMS from the layer.

Implementation should:

1. Check if there is QGIS style to a layer
2. How many layers are in WFS
3. How many styles are there for a layer (pick the first one?)

**Comment by MikhanGusev** [comment]
Added in 0.12.7
