### ISSUE TITLE
Падение QGIS при старте, если подключени к веб ГИС недоступно

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_connect#157]
При старте QGIS если в NextGIS Connect есть подключение к веб ГИС и эта веб ГИС недоступна, то происходит падение.
В качестве обходного пути необходимо удалить подключение в реестре/настройках.

Ожидаемое поведение - падения быть не должно.

**Comment by alisovenko** [comment]
А какая версия плагина?
На могу воспроизвести на 0.11.5
Веб ГИС недоступна - это значит что она не существет? например,
http://nonexistent.nextgis.com/

**Comment by BishopGIS** [comment]
Версия последняя 0.11.5

Воспроизводить нужно так:
1. Создаешь подключение к реальной веб-ГИС
2. Отключаешь от интернета
3. Перезапускаешь QGIS

На mac не воспроизводится. 
@simgislab у тебя на Windows воспроизводится?

**Comment by alisovenko** [comment]
С отключением интернета на Windows 10 тоже что-то не воспроизведу.

**Comment by simgislab** [comment]
никаких проблем

![](http://m-d.me/img/ss/I4py2TkDql.png)

**Comment by alisovenko** [comment]
В предыдущих версиях плагина точно были падения.

**Comment by alisovenko** [comment]
Воспроизвел.
Если инстанс на https, а в настройках http. 
Тогда есть падение.

**Comment by BishopGIS** [comment]
Еще дополнительная информация - у клиента используется прокси.
