### ISSUE TITLE
Overwrite selected layer fails with Polygonz/LineZ

### ISSUE THREAD

**Issue by Romchik93** [nextgis/nextgis_connect#158]
1. Делаю импорта слоя в Веб ГИС через NextGIS Connect.
1.1. Могу отредактировать слой после этого, а могу и нет.
2. Делаю Overwrite selected layer.
Не перезаписывается: Ошибка - "При обработке запроса возникла внутренняя ошибка или сервер настроен некорректно и не может обработать запрос.. URL http://romangis.nextgis.com//api/resource/47/feature/"  УРЛ пустой
Примеры данных [LinestringZ.zip](https://github.com/nextgis/nextgis_connect/files/4197336/LinestringZ.zip)

Ожидаемое поведение - должен перезаписать слой в Веб ГИС без ошибок

**Comment by simgislab** [comment]
Потому что это:

> Line (WKB type: "LineStringZ")

**Comment by alisovenko** [comment]
Кажется что все нормально в коннекте.
Задал вопрос в НГВ.

PATCH на https://sandbox.nextgis.com/api/resource/2192/feature/

тело запроса:
 `[{"fields": {"fid": 1}, "geom": "LineStringZ (4155999.50808637123554945 7553558.53270144388079643 100, 4156939.05070395348593593 7552891.32127736136317253 80, 4158450.48882788745686412 7552196.87673393171280622 70, 4159757.67855669604614377 7552115.17737588379532099 50, 4160806.15365167707204819 7552196.87673393171280622 40, 4162086.11026113433763385 7552441.97480808477848768 10, 4165313.23490413092076778 7553299.81806761771440506 0)"}]`

результат:
`{"title": "Internal server error", "message": "The server encountered an internal error or misconfiguration and was unable to complete your request.", "exception": "nextgisweb.pyramid.exception.InternalServerError", "status_code": 500, "guru_meditation": "711c86cfb77cf418508f31cf6be2de8d"}`

**Comment by alisovenko** [comment]
Ошибка есть - неверно сформированный wkt

**Comment by alisovenko** [comment]
Сделан фикс в версии 0.11.7-0
Доступно dev репозитории:
https://rm.nextgis.com/api/repo/10/qgis_xml

**Comment by alisovenko** [comment]
Еще рано закрывать я не зафиксировал изменения

**Comment by alisovenko** [comment]
Done
