### ISSUE TITLE
Если в конце URL есть / выдаёт ошибку.

### ISSUE THREAD

**Issue by pamfilov** [nextgis/nextgis_connect#160]
При указании правильного URL выдаёт ошибку, если в конце есть /

![error](https://user-images.githubusercontent.com/8543523/87551612-4bbabc80-c6b9-11ea-803a-7993bf970050.png)
![noerror](https://user-images.githubusercontent.com/8543523/87551701-6856f480-c6b9-11ea-8186-afc43879ba07.png)

**Comment by Romchik93** [comment]
Кстати не всегда, иногда ровно наоборот - со слешем работает, без нет.

**Comment by MikhanGusev** [comment]
@Romchik93 пришли пример твоего случая, если есть

**Comment by MikhanGusev** [comment]
Сделал удаление последнего слеша в этом диалоге всегда, подразумевая что сам url вводимый пользователем нигде в плагине в чистом виде не используется (только например с добавлением /api/...) => можно его всегда удалять
