### ISSUE TITLE
Не переводится интерфейс на русский язык. Все остается на английском при любом языке интерфейса NextGIS QGIS

### ISSUE THREAD

**Issue by Romchik93** [nextgis/nextgis_connect#163]
Ожидаемое поведение: при выборе русского языка для NextGIS QGIS, NextGIS Connect должен переходить также на русский

**Comment by MikhanGusev** [comment]
Сгенерировал и добавил вручную файлы *.qm. Дальнейшие шаги зависят от автоматической системы сборки плагина, если такая будет
