### ISSUE TITLE
Исправлять ошибку геометрии при загрузке - незамкнутый полигон

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#166]
Сейчас не исправляется несмотря на галку "Исправлять невалидные геометрии"

Пример 
[federal_oopt_rd.zip](https://github.com/nextgis/nextgis_connect/files/5702470/federal_oopt_rd.zip)

**Comment by MikhanGusev** [comment]
Исправлена ошибка при импорте в NGW, но пока не добавлено само исправление геометрии
