### ISSUE TITLE
Needs QT5 Core

### ISSUE THREAD

**Issue by rougerouter** [nextgis/nextgis_connect#170]
Won't work with QGIS 3.16 error when trying to install:
Couldn't load plugin 'nextgis_connect' due to an error when calling its classFactory() method 

ImportError: PyQt4 classes cannot be imported in QGIS 3.x. Use PyQt5.QtCore or the version independent qgis.PyQt.QtCore import instead.

**Comment by simgislab** [comment]
QGIS 3 version is due to be released this week

If you'd like to try it sooner, let us know as https://t.me/nextgis_talks or via info@nextgis.com
