### ISSUE TITLE
Ошибка создания WMS сервиса из панели Connect

### ISSUE THREAD

**Issue by eduard-kazakov** [nextgis/nextgis_connect#172]
После диалога выбора стиля (при выборе в контекстном меню "Create WMS Service" возникает ошибка:

AttributeError: 'NGWLayerStyleChooserDialog' object has no attribute 'needCreateNewStyle' 
Traceback (most recent call last):
  File "C:/NextGIS/share/ngqgis/python/plugins\nextgis_connect\tree_panel.py", line 933, in create_wms_service
    if not dlg.needCreateNewStyle() and dlg.selectedStyle():
AttributeError: 'NGWLayerStyleChooserDialog' object has no attribute 'needCreateNewStyle'

**Comment by MikhanGusev** [comment]
Fixed in 0.12.3
