### ISSUE TITLE
Переименование ресурса в плагине не обновляет дерево в нем же

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_connect#173]
При переименовании векторного слоя через NextGIS Connect, в NGW все корректно переименовывается. Однако в NextGIS Connect переименование не показывается (векторный слой по факту переименовывается, но в дереве слоев остается прежнее наименование).

![image](https://user-images.githubusercontent.com/1708122/136033723-462b936b-f037-4663-89f4-611d5ec6333f.png)

![image](https://user-images.githubusercontent.com/1708122/136033786-e91a29a1-34a6-4728-9a55-01da01318106.png)

**Comment by MikhanGusev** [comment]
Исправлено в 0.12.18
