### ISSUE TITLE
Не обрезает gpkg по 180 меридиану при отправке через NextGIS Connnect

### ISSUE THREAD

**Issue by Romchik93** [nextgis/nextgis_connect#176]
[Polta1_FO2019.zip](https://github.com/nextgis/nextgis_connect/files/8853247/Polta1_FO2019.zip)

**Comment by Romchik93** [comment]
0. Распаковать (gpkg нельзя прикрепить в гит)
- Открыть в NextGIS QGIS
- Импортировать слой через Коннект 
- Слой не обрезан

**Comment by BishopGIS** [comment]
Обрезку можно делать вот так:

ct = osr.CoordinateTransformation(lyr.GetSpatialRef(), srs3857)
transformer = ogr.GeomTransformer(ct, ['WRAPDATELINE=YES', 'DATELINEOFFSET=35'])

ну либо свой реализацию (есть в скриптах пакетной загрузки) - см. testing/-/blob/master/demo/vmap2eeko.py

**Comment by MikhanGusev** [comment]
Исправлено в версии 0.14.3
