### ISSUE TITLE
Ломаются системы координат при загрузке на сервер

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#18]
Открываю QGIS 2.14.2 в Ubuntu
Обновляю репозиторий ngw_connect до 0.4.10
Подкладываю mapnik.
Делаю временный точечный слой, рисую несколько точек. Сохраняю этот временный слой в GeoJSON в 4326. Загружаю GeoJSON через NGW Connect в instance.nextgis.com.

Там он на карте не рисуется.
Выгружаю через веб-интерфейс geojson, открываю в QGIS - координаты улетают в океан.

Хидер geojson таков
```
{"crs": {"type": "name", "properties": {"name": "EPSG:3857"}}, "type": "FeatureCollection", "features": [{"geometry": {"type": "Point", "coordinates": [73026.06241254183, 131011.42642776956]}, 
```

**Comment by trolleway** [comment]
[geojsoncrisis.zip](https://github.com/nextgis/ngw_connect/files/270264/geojsoncrisis.zip)

**Comment by trolleway** [comment]
При ручной загрузке исходного файла geojson через веб-интерфейс, отображение работает правильно.

**Comment by alisovenko** [comment]
Не получается воспроизвести.
Но я проверяю на 0.4.11.
Из geojsoncrisis.zip я извлек SOURCEFILE.geojson, загрузил в qgis - там 4 точки вокруг Москвы.
Загрузил этот слой в NGW через connect и добавил этот слой на карту - все точки в ngw на месте.
Выгружаю из NGW json - тоже все ОК.

**Comment by simgislab** [comment]
@trolleway перепроверь, пожалуйста и закрой если не воспроизводится

**Comment by alisovenko** [comment]
Не воспроизводится в NG Connect 0.7.x
