### ISSUE TITLE
Error when add WFS service from Postgis Layer to QGIS Software

### ISSUE THREAD

**Issue by tranquocnhat** [nextgis/nextgis_connect#188]
I just add vector source and postgis source to my nextgisweb after that i add WFS service for QGIS client but only vector source can export and postgis layer have error as image below.
I also check all in Diagnostics everything be ok. But i try add WFS as service in panel is ok and use Add to QGIS in plugin is error
![Screenshot 2023-03-02 141034](https://user-images.githubusercontent.com/23132487/222662541-d9ac0477-85d8-47ad-bf8d-522478c0cdca.png)
![Screenshot 2023-03-02 141237](https://user-images.githubusercontent.com/23132487/222662556-20ff8fea-8e92-4c43-92d2-0ba815940ee3.png)
![Screenshot 2023-03-02 141324](https://user-images.githubusercontent.com/23132487/222662561-e4237350-57c1-423d-8bd9-b8714a480f98.png)
![Screenshot 2023-03-02 141738](https://user-images.githubusercontent.com/23132487/222662569-c1fdb442-d4d5-4e3f-86b2-5ab66dbdde2d.png)
![Screenshot 2023-03-02 141745](https://user-images.githubusercontent.com/23132487/222662573-d9006970-4314-4b88-92bf-7ab185a94462.png)
![Screenshot 2023-03-02 141804](https://user-images.githubusercontent.com/23132487/222662578-75474fc4-99df-483c-a306-99eac9e06da8.png)

**Comment by simgislab** [comment]
I can confirm this.

Note that the created WFS service works well if you add it via regular Add layer - WFS, but not with Connect.

We'll have a look at this.

**Comment by ivanbarsukov** [comment]
Fixed in [1.5.4](https://github.com/nextgis/nextgis_connect/releases/tag/1.5.4)
