### ISSUE TITLE
Text and branding fixes

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#19]
NG Connect -> NextGIS Connect

NGW Resources -> NextGIS Resources
NGW Connect settings -> Settings

**Comment by Kinda-me** [comment]
![ng connect](https://cloud.githubusercontent.com/assets/6493848/15609972/a0a92cac-242b-11e6-8932-461cb7c7218e.png)

Предлагаю поменять на:

"No active connections to NextGIS.com. Please create a connection. You can get your free Web GIS here."
