### ISSUE TITLE
Add help

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#25]
button with question mark that sends to a webpage somewhere here

http://docs.nextgis.ru/docs_ngcom/source/toc.html

@Kinda-me please add link here when this section is ready

link should be language specific (RU/EN)

**Comment by Kinda-me** [comment]
Link will be:

RU: http://docs.nextgis.ru/docs_ngcom/source/ngqgis_connect.html
EN: http://docs.nextgis.com/docs_ngcom/source/ngqgis_connect.html

Links don't work yet.

**Comment by BishopGIS** [comment]
I think QGIS plugin's documentation should be here: http://docs.nextgis.ru/docs_ngqgis/source/plugins.html

**Comment by Kinda-me** [comment]
Ideally full plugin documentation should be in docs_ngqgis, and quick how-to in docs_ngcom (with references to full documentation).

**Comment by alisovenko** [comment]
Don't like the icon in the toolbar. Make a link at the bottom of the plugin panel.
