### ISSUE TITLE
Don't show Main group resources

### ISSUE THREAD

**Issue by alisovenko** [nextgis/nextgis_connect#35]
What do you think about it?
Advantage is space saving

**Comment by alisovenko** [comment]
Not a good idea. In this case, is not a good way to create a resource in the root group.

**Comment by simgislab** [comment]
but why? we have https://github.com/nextgis/nextgis_connect/issues/26

**Comment by alisovenko** [comment]
White space may not present, if there are a lot of resources

**Comment by simgislab** [comment]
we have 'Create new group', it doesn't need whitespace
and we can't create other resources in this mode

**Comment by alisovenko** [comment]
If we already select any group, i don't know how we can create resource in root group.
Need way to deselect resourc, in case when there is no white space.

**Comment by simgislab** [comment]
>If we already select any group, i don't know how we can create resource in root group
Easy. Select a resource other then a group in main group.

**Comment by alisovenko** [comment]
I think it's a bad case.
If all resources in second level are resources.
