### ISSUE TITLE
Error while upload layer to ngw, if instance installed without QGIS render

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#36]
Instance on standalone server
![2016-06-02 16-35-27](https://cloud.githubusercontent.com/assets/4630662/15746679/3ba03b66-28e0-11e6-97b0-07dedbbc51be.png)

**Comment by alisovenko** [comment]
Не воспроизводится в NG Connect 0.7.x

**Comment by MikhanGusev** [comment]
Duplicate for #132
