### ISSUE TITLE
Нет проверки на обязательные поля в настройках

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgis_connect#40]
Форма ввода параметров соединения позволяет нажать OK при пустых полях:
![image](https://cloud.githubusercontent.com/assets/1277422/15748299/0c2327d4-28e7-11e6-9e77-98b668f515ea.png)

![image](https://cloud.githubusercontent.com/assets/1277422/15748322/236684b8-28e7-11e6-8d26-b9c34c408fef.png)

Необходимо либо блокировать кнопку ОК, либо выводить предупреждение и отменять закрытие формы

**Comment by alisovenko** [comment]
Обязательные поля теперь не могут быть пустыми.
