### ISSUE TITLE
Переключение в Расширенный режим приводит к потере соединения из списка

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgis_connect#41]
Наверное это следствие #40.
При переключении в расширенный режим и нажатии кнопки ОК, форма закрывается и соединение пропадает из списка.
Аналогичное поведение если из расширенного режима переключиться в простое.

**Comment by alisovenko** [comment]
Убрал расширенный режим для формы.
Обязательные поля теперь не могут быть пустыми.
