### ISSUE TITLE
Trailing / symbol in URL

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#45]
We have a standalone installation of NGW
http://opendata25.primorsky.ru/ngw/ - return in browser "ERR_EMPTY_RESPONSE"
http://opendata25.primorsky.ru/ngw - redirect in browser to "/resource/0" and open. 
So user can think second url is normal.

nextgis_connect can not open http://opendata25.primorsky.ru/ngw, only http://opendata25.primorsky.ru/ngw/ (with trailing /)

**Comment by trolleway** [comment]
Но может это и веб не так запущен.

**Comment by alisovenko** [comment]
Ошибка еще воспроизводится?

**Comment by trolleway** [comment]
Теперь работает
