### ISSUE TITLE
Edit connection, button Ok disabled always

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#46]
![2016-06-08 13-21-54](https://cloud.githubusercontent.com/assets/4630662/15891252/5aee2ab4-2d7c-11e6-9cf7-a16ca9c2e92b.png)

**Comment by simgislab** [comment]
http://opendata25.primorsky.ru/ngw - такой адрес работает.

@alisovenko мы можем этот кейс обрабатывать и пробовать проверять С и БЕЗ последнего слэша? И автоматом его, например убирать, если надо было без.

**Comment by alisovenko** [comment]
У меня работает и c '\' на конце и без.
Не совсем понял в чем ошибка.

Кнопка 'ОК' недоступна т.к. url не корректный - видимо сервер не доступен был.
Именно это поведение вы считаете некорректным?

**Comment by simgislab** [comment]
действительно, работает и так и так, но точно не работало, возможно какие-то изменения на сервере произошли.

закрываю
