### ISSUE TITLE
Password check while edit connection needed

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#49]
Сейчас пишет "Успешное подключение", хочу ещё такую же надпись "Подключение по паролю/Гостевое подключение".
![2016-06-10 15-21-32](https://cloud.githubusercontent.com/assets/4630662/15964034/0b5b6328-2f1f-11e6-9e85-94a0f94729bb.png)

Я случайно ввёл пароль в неправильной раскладке, и целый день не мог ничего понять.

**Comment by trolleway** [comment]
Или сделать как в Manager - кнопку "Тестировать подключение", которая выводит сообщение "Авторизовался" или "Подключился как гость".
Или сделать кнопку "Показать пароль". Но мне больше нравится, чтоб программа сама проверяла подключение.

**Comment by ivanbarsukov** [comment]
Released in 2.0
