### ISSUE TITLE
При открытии карты подставляется имя пользователя и пароль

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#6]
Ссылка типа: administrator:pass@176.9.38.120/practice2/resource/250/display

Это баг или фича? Мне кажется баг.

**Comment by yellow-sky** [comment]
Это фича. Ты не сможешь открыть карту, если у гостя нет прав на неё. а
открывает он из плагина, из настроенного соединения

2016-05-11 21:31 GMT+03:00 Maxim Dubinin <notifications@github.com>:

> Ссылка типа:
> administrator:pass@176.9.38.120/practice2/resource/250/display
>
> Это баг или фича? Мне кажется баг.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/nextgis/ngw_connect/issues/6>
>



-- 

Best regards,

Nikulin Eugeny

**Comment by simgislab** [comment]
у меня браузер (ФФ) ругается на такое

**Comment by simgislab** [comment]
у WMS/WFS тоже так?
