### ISSUE TITLE
Создаваемые стили должны называться так же как слой

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#61]
При загрузке слоя к нему создаётся стиль с добавлением "-style". Такое добавление не нужно, потому что при создании веб-карты его приходится вручную стирать у 50 слоёв.

**Comment by trolleway** [comment]
Если стиль с таким именем уже есть - то тогда добавлять: -2, -3...

**Comment by simgislab** [comment]
а зачем его стирать?

**Comment by trolleway** [comment]
Потому что тогда на веб-карте в списке слоёв везде пишется -style

**Comment by alisovenko** [comment]
Стили должны иметь отличное название от слоя т.к. их может быть много у одного слоя.
А вот в NGW в дереве слоев на карте, мне кажется, лучше отображать не имена стилей а имена слоев.

**Comment by simgislab** [comment]
>в NGW в дереве слоев на карте, мне кажется, лучше отображать не имена стилей а имена слоев
да да

**Comment by BishopGIS** [comment]
На одну карту можно добавить несколько стилей и как их отличать? Это может быть нужно если часть данных стилем скрыто или иное отображение одних и тех же данных.

**Comment by alisovenko** [comment]
> На одну карту можно добавить несколько стилей и как их отличать?

А такое точно бывает нужно? - это не задача стиля? - нужно сделать  правильный стиль, чтобы не добавлять два разных стиля одного слоя.

ну, все равно, в этом случае, мне кажется, данная задача не поможет

**Comment by BishopGIS** [comment]
В manager мы к имени слоя добавляем "_style" - и также инкрементно по циферке в конец, если такой стиль уже есть. Переименовать всегда потом можно.

**Comment by simgislab** [comment]
-style  в названии на карте выглядит уродливо, я за то, что если один и тот же слой добавлен 2 раза с разными стилями, то пусть он лучше будет одинаково назван в списке слоёв, но без -style

**Comment by BishopGIS** [comment]
Не получится. Дублировать имена нельзя. Тогда "имя слоя", "имя слоя 1" ... "имя слоя n"

**Comment by simgislab** [comment]
мы же про имена в списке слоёв сейчас, там что угодно может дублироваться

**Comment by BishopGIS** [comment]
Тогда этот тикет (про названия слоев в дереве карты) дожен быть в https://github.com/nextgis/nextgisweb/issues

**Comment by simgislab** [comment]
не, речь про display name, он может быть одинаковым для разных стилей и лучше чтобы он не имел суффикса -style, только и всего

**Comment by alisovenko** [comment]
Т.е. оставляем все как есть?
Сейчас имя стиля - <имя слоя>+"-style" + "(N)"
Эту задачу я закрываю?

**Comment by BishopGIS** [comment]
Я так понял Максима - имя слоя в карте должно равняться <имя слоя>. А стили - да как было, не меняются.

**Comment by alisovenko** [comment]
В этой задаче речь идет только о импорте (создании) слоя в NGW и, как следствие, создание стиля.
Помещение на карту этого стиля производится в интерфейсе NGW.

При импорте всего проекта происходит создание карты, где в качестве имени слоя в дереве слоев ngw помещается имя соответствующего слоя из QGIS - это так сейчас работает.

**Comment by simgislab** [comment]
да, что-то мы все немного о разном)
