### ISSUE TITLE
DeprecationWarning: QgsMapCanvas.mapRenderer() is deprecated

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#63]
В консоли предупреждение Python вывалилась эта ошибка после импорта проекта. Проект вроде успешно импортировался. 
![image](https://cloud.githubusercontent.com/assets/4630662/16654643/5c8815ca-445f-11e6-93da-e875885d7cd3.png)

**Comment by alisovenko** [comment]
duplicate #44
