### ISSUE TITLE
Create a web map

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#66]
Similarly to Create WFS service lets add Create Web map to right click on a layer.

A checkbox like #65 can be added to open web map right after creation.

**Comment by simgislab** [comment]
map from a layer should also use the extent of this layer and style

if style doesn't exist - give a warning and ask to create one first

**Comment by alisovenko** [comment]
nextgis/ngw_external_api_python#4

**Comment by alisovenko** [comment]
- nextgis/ngw_external_api_python#4

**Comment by alisovenko** [comment]
If the style single, creation webmap dialog is not need.
