### ISSUE TITLE
Мультиточечный слой

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#67]
Не знаю в какой из 4 репозиториев это заносить.

Коннекчусь по WFS к слою, заношу точки. При сохранении мультиточки выдаётся ошибка: "  Ответ сервера имеет неизвестный тег: html"
Ожидаемое поведение: текст ошибки должен быть: "Слой не поддерживает мультиточки, а только точки", или же в NextGIS Connect иконки слоя WFS должны быть разные для точечного и мультиточечного слоя.

![image](https://cloud.githubusercontent.com/assets/4630662/16712535/d220c630-4692-11e6-84f6-4a2d08749aad.png)

**Comment by simgislab** [comment]
should work now, lots has changed, reopen if needed
