### ISSUE TITLE
Incorrect calculation of extent

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#68]
QGIS Map

https://www.dropbox.com/s/fhjzy1fj2kos3pb/russia.png?dl=0

http://examples.nextgis.com/resource/112/update

need to check

**Comment by drnextgis** [comment]
@alisovenko посмотри, мне кажется у нас как минимум неправильно вычисляется охват карты, если ее охват пересекает 180 меридиан. На скриншоте пример того как сейчас вычисляется и чуть ниже мой исправленный вариант.

![ng_connect](https://cloud.githubusercontent.com/assets/866124/17033999/ee9c36a2-4faa-11e6-85d6-064b411c605e.png)

**Comment by drnextgis** [comment]
Ещё нужно разбивать экстент по типу как тут: https://github.com/qgis/QGIS/blob/master/src/core/qgsmaprenderer.cpp#L690

**Comment by alisovenko** [comment]
Сделали в NG Connect 0.7.6
