### ISSUE TITLE
Print layer name in error message

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#70]
![2016-07-28 13-49-31](https://cloud.githubusercontent.com/assets/4630662/17210261/25f528d8-54ca-11e6-97d9-9e29de56ff14.png)

При импорте проекта приходится вручную перебирать атрибуты всех слоёв, что бы найти поле с недопустимым именем

**Comment by trolleway** [comment]
А дай-ка я сам попробую это написать

**Comment by alisovenko** [comment]
Done in version 0.7.11
