### ISSUE TITLE
Error while upload corrupt (or not?) shapefile to NGW

### ISSUE THREAD

**Issue by MikhanGusev** [nextgis/nextgis_connect#73]
Create simple Shapefile in NextGIS QGIS 16.1.140 and add one field to it. Got this error while saving, but the layer **created and saved successfully**. EDIT: found that this occures when creating the text field with 255 length, but in some other situations too (attached a file).

![s1](https://cloud.githubusercontent.com/assets/6196272/17514762/06dd3f72-5e3d-11e6-933a-270e9b825df2.PNG)

After that load this layer to NGW via NextGIS Connect 0.7.6. QGIS crashes with this (can't expand error's window):

![s2](https://cloud.githubusercontent.com/assets/6196272/17514786/34b33726-5e3d-11e6-97ea-b615fe2bcd71.PNG)

**Comment by simgislab** [comment]
please attach a file to reproduce this, thanks

**Comment by MikhanGusev** [comment]
[wolf.zip](https://github.com/nextgis/nextgis_connect/files/408918/wolf.zip)

**Comment by MikhanGusev** [comment]
The same error if:
1) Open QGIS. Create new void point temporary scratch layer.
2) Create fields: a) Text (length 255), b) Date, c) Time, d) Date&Time.
3) Save layer -> success.
4) NextGIS Connect -> Iport current project -> QGIS crashes with same error (can not see details of that)

**Comment by MikhanGusev** [comment]
Possible reason: some fields were named as "id" or some other errors from here: http://docs.nextgis.ru/docs_ngcom/source/data_upload.html#ngcom-vector-layer

**Comment by simgislab** [comment]
same error and QGIS crashes on Ubuntu

everything imports fine if, before upload

1. id is removed
2. one point is added

**Comment by simgislab** [comment]
see #75 and #76
