### ISSUE TITLE
Rename field id on upload

### ISSUE THREAD

**Issue by simgislab** [nextgis/nextgis_connect#76]
if it exists in input dataset, for example to _id

this has to stop!)

note that this will have to be reverted sometime in the future, when NGW learn how to deal with ID in a correct way

**Comment by BishopGIS** [comment]
Let have unique rules for field rename. In manager is done so:
1. Add number 1 to field name (in case id - id1)
2. If such name exist increase number (id2) until unique field name will be form.

**Comment by simgislab** [comment]
same goes to field 'type'

**Comment by BishopGIS** [comment]
Also changing field names must be reported and qml style fixed.

**Comment by BishopGIS** [comment]
Upload requirements from http://docs.nextgis.com/docs_ngweb/source/layers.html#ngw-create-vector-layer

   Output file should not have invalid geometries (QGIS tool should output an empty list of invalid   geometries), dates should not have NULL values, there should not be attribute names: id (ID), type(TYPE), source(SOURCE).

**Comment by simgislab** [comment]
https://github.com/nextgis/nextgis_connect/issues/77

**Comment by alisovenko** [comment]
Why is it necessary?
The user knows that it is impossible to load layers with field "id".
If he tries to do it, he will get error from server.

In QGIS he have good instrument for rename this field as he pleases.

**Comment by BishopGIS** [comment]
The problem is that NextGIS QGIS add field named 'id' as default to new layer and nextgis.com cannot accept such layer. Two products from one company not work together. This is some kind of cognitive dissonance.

**Comment by simgislab** [comment]
also, lots of our users don't know how to rename fields and we shouldn't make them learn it.

again, if we provide #77 they can opt out and do it themselves if they like

**Comment by simgislab** [comment]
Doesn't work for fields named ID

**Comment by alisovenko** [comment]
I cann't reproduce it.
If I create shape file with field ID by "New shape Layer" the layer is added to webgis successfully. Field 'ID' is renamed to 'ID1'

**Comment by simgislab** [comment]
can't reproduce too
