### ISSUE TITLE
Модуль открывает имеющийся WFS с версией 1.1, а она не поддерживается в NGW

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#84]
### Шаги для воспроизведения
1. Создать в NGW WFS-сервис вручную
2. Подключится к NGW в NextGIS Connect
3. Добавить из NextGIS Connect WFS-сервис на карту
#### Фактическое поведение

Добавляется слой WFS версии 1.1, а веб её не поддерживает, поэтому фичи не добавляются
#### Ожидаемое поведение

В QGIS должен добавляться слой другой версии, спроси у @BishopGIS

**Comment by alisovenko** [comment]
Какая версия NGW?
Какая версия QGIS?

Не воспроизводится для nextgis.com (nextgisweb 3.0) и QGIS 2.14.5 (NGQ 16.2.144)
Layer source для добавленного в QGIS wfs имеет параметры:
SERVICE=WFS&TYPENAME=buildings&srsname=EPSG:3857&VERSION=1.0.0&REQUEST=GetFeature

**Comment by simgislab** [comment]
lack of feedback, reopen if necessary
