### ISSUE TITLE
Не добавляются слои WFS

### ISSUE THREAD

**Issue by yellow-sky** [nextgis/nextgis_connect#93]
В qgis 2.16.1 при добавлении сервиса на карту из облачного инстанса создается только группа для слоев. Сами слои не появляются на карте.
Подозрение - версия протокола выбирается автоматом и конечно же 1.1 )

**Comment by simgislab** [comment]
в 2.16.3 у меня добавлются, правда есть сообщение о неверном охвате

![](http://m-d.me/img/ss/20161010-307-201kb.jpg)
