### ISSUE TITLE
Не работает сортировка слоёв в группе ресурсов

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#97]
![2016-10-21 14-33-51](https://cloud.githubusercontent.com/assets/4630662/19597173/95a61fde-979b-11e6-8c39-ce14b4a7f521.png)

**Comment by alisovenko** [comment]
Уточни, пожалуйста, версию плагина.

**Comment by trolleway** [comment]
В новой версии всё работает
