### ISSUE TITLE
Можно загрузить слой с русским названием в веб, но потом его нельзя добавить как WFS

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#98]
# Шаги для повторения
1. Создать точечный слой с русским названием в QGIS.
2. Загрузить в nextgis.com через nextgis_connect
3. Создать в nextgis_connect wfs-сервис из этого слоя.
# Текущее поведение

В QGIS добавляется только пустая группа, сообщение об ошибке:
`
Could not find the layer '%D0%BC%D1%84%D1%86_3': Check your config file for the missing layer. (Available layers are: мфц_3).
`
В вебе: 
![2016-10-28 18-59-54](https://cloud.githubusercontent.com/assets/4630662/19813058/c1f4a060-9d40-11e6-9098-0d6a322206d7.png)
# Ожидаемое поведение

При создании wfs-сервиса nextgis_connect должен делать keyname транслитом

**Comment by ABiatov** [comment]
confirmed
