### ISSUE TITLE
Update layer

### ISSUE THREAD

**Issue by trolleway** [nextgis/nextgis_connect#99]
Пользователь указывает локальный слой и слой в вебе, нажимает кнопку "Заменить слой в вебе".
Слой заменяется, используя комманды API "Удалить все фичи в слое" и "Добавить одну новую фичу".

Это будет замена такому workflow: _создать wfs, получить через него слой, удалить вручную все фичи, скопировать в него через буфер фичи из локального слоя_.

Преимущество: в протоколе wfs есть ограничение на максимальное количество передаваемых фич, а в REST API - нет. Но загрузка фич по одной будет идти медленно, поэтому нужно предусмотреть, что в REST API может появится запрос "Загрузить в слой сразу пачку фич".

Может возникнуть ситуация, что у локального слоя и у слоя в вебе разные наборы атрибутов и тип геометрии. Поведение в этом случае должно быть таким же как при копировании-вставке объектов между слоями в qgis

**Comment by trolleway** [comment]
А теперь для этого появился запрос PATCH

**Comment by alisovenko** [comment]
You can try this with 0.10.7.1 (dev)

**Comment by alisovenko** [comment]
Done
